name: Software documentation

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout software
        uses: actions/checkout@v2

      - name: Create documentation directory
        run: |
          mkdir -p docs/Software/respi-firmware

      - name: Generate documentation for respi-firmware
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: 'src/software/firmware/Doxyfile'

      - name: Archive documentation
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs/Software/

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: docs
          TARGET_FOLDER: ./software/firmware/
