name: Telemetry

on:
  push:
    paths:
      - .github/workflows/**
      - src/software/telemetry/**

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Go to telemetry directory
        run: |
          cd src/software/telemetry || exit 1

      - name: Lint
        uses: actions-rs/clippy-check@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings

      - name: Check code style
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --all -- --check

      - name: Build lib
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build

      - name: Test lib
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test

      - name: Build debug tool
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --bin telemetry_debug --features="build-binary" --release

      - name: Archive binary
        uses: actions/upload-artifact@v1
        with:
          name: telemetry_debug
          path: src/software/telemetry/target/release/telemetry_debug
